function createplot(Y1, Parent1)
%CREATEPLOT(Y1, PARENT1)
%  Y1:  vector of y data
%  PARENT1:  plot parent

%  Auto-generated by MATLAB on 26-Jan-2016 00:10:11

% Create plot
Y1(1,1)
plot(Y1,'Parent',Parent1);

